import React from "react";
import TourCard from "./TourCard";

export default function TourList() {
  const tours = [
    {
      id: 1,
      path: "abu-dhabi-city-tour",
      image: "https://images.unsplash.com/photo-1590822067318-d58785999ad3?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1032",
      category: "Guided Tours",
      rating: "4.5",
      reviews: "318",
      title: "Discover Abu Dhabi: Iconic Landmarks & Hidden Gems",
      details: [
        "Explore the ‘home of luxury’, Inside Burj Al Arab, on this 90-minute tour.",
        "Accompanied by a butler, enter the Royal Suite of this 7-star hotel.",
        "Learn about its iconic design and history in this immersive experience.",
        "Experience Emirati hospitality and capture stunning moments.",
        "Visit the boutique and take home curated souvenirs.",
      ],
      price: "AED 399",
      duration: "1 hr. 30 min.",
      cancellation: "Free cancellation",
      bookNowText: "Book now, pay later",
      showInfoText: "Show inclusions & important info →",
    },
    {
      id: 2,
      path: "adventure-tours",
      image: "https://plus.unsplash.com/premium_photo-1694475175003-9b470d82de5e?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1171",
      category: "Adventure Tours",
      rating: "4.7",
      reviews: "210",
      title: "Thrill Seekers’ Adventure: Adrenaline-Packed Experiences",
      details: [
        "Explore the ‘home of luxury’, Inside Burj Al Arab, on this 90-minute tour.",
        "Accompanied by a butler, enter the Royal Suite of this 7-star hotel.",
        "Learn about its iconic design and history in this immersive experience.",
        "Experience Emirati hospitality and capture stunning moments.",
        "Visit the boutique and take home curated souvenirs.",
      ],
      price: "AED 195",
      duration: "6 hr.",
      cancellation: "Free cancellation",
      bookNowText: "Reserve now, pay later",
      showInfoText: "Show inclusions & important info →",
    },
    {
      id: 3,
      path : "burj-khalifa",
      image: "https://images.unsplash.com/photo-1582120031356-35f21bf61055?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=687",
      category: "Adventure Tours",
      rating: "4.7",
      reviews: "210",
      title: "Reach New Heights: Burj Khalifa Observation Deck Experience",
     details: [
        "Explore the ‘home of luxury’, Inside Burj Al Arab, on this 90-minute tour.",
        "Accompanied by a butler, enter the Royal Suite of this 7-star hotel.",
        "Learn about its iconic design and history in this immersive experience.",
        "Experience Emirati hospitality and capture stunning moments.",
        "Visit the boutique and take home curated souvenirs.",
      ],
      price: "AED 179",
      duration: "6 hr.",
      cancellation: "Free cancellation",
      bookNowText: "Reserve now, pay later",
      showInfoText: "Show inclusions & important info →",
    },
    {
      id: 4,
      path: "desert-safari-with-dinner",
      image: "https://images.unsplash.com/photo-1684137557817-d5fc4d3ccf69?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1170",
      category: "Adventure Tours",
      rating: "4.7",
      reviews: "210",
      title: "Magical Desert Safari & Arabian Dinner Under the Stars",
      details: [
        "Explore the ‘home of luxury’, Inside Burj Al Arab, on this 90-minute tour.",
        "Accompanied by a butler, enter the Royal Suite of this 7-star hotel.",
        "Learn about its iconic design and history in this immersive experience.",
        "Experience Emirati hospitality and capture stunning moments.",
        "Visit the boutique and take home curated souvenirs.",
      ],
      price: "AED 340",
      duration: "6 hr.",
      cancellation: "Free cancellation",
      bookNowText: "Reserve now, pay later",
      showInfoText: "Show inclusions & important info →",
    },
    {
      id: 5,
      path: "dhow-cruise",
      image: "https://images.unsplash.com/photo-1515678821046-f1ba75cb9f9e?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1170",
      category: "Adventure Tours",
      rating: "4.7",
      reviews: "210",
      title: "Serene Dhow Cruise: Sunset & Dinner on Dubai Creek",
      details: [
        "Explore the ‘home of luxury’, Inside Burj Al Arab, on this 90-minute tour.",
        "Accompanied by a butler, enter the Royal Suite of this 7-star hotel.",
        "Learn about its iconic design and history in this immersive experience.",
        "Experience Emirati hospitality and capture stunning moments.",
        "Visit the boutique and take home curated souvenirs.",
      ],
      price: "AED 399",
      duration: "6 hr.",
      cancellation: "Free cancellation",
      bookNowText: "Reserve now, pay later",
      showInfoText: "Show inclusions & important info →",
    },
    {
      id: 6,
      path: "dubai-city-tour",
      image: "https://plus.unsplash.com/premium_photo-1697729914552-368899dc4757?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1112",
      category: "Adventure Tours",
      rating: "4.7",
      reviews: "210",
      title: "Dubai City Explorer: Modern Marvels & Cultural Wonders",
      details: [
        "Explore the ‘home of luxury’, Inside Burj Al Arab, on this 90-minute tour.",
        "Accompanied by a butler, enter the Royal Suite of this 7-star hotel.",
        "Learn about its iconic design and history in this immersive experience.",
        "Experience Emirati hospitality and capture stunning moments.",
        "Visit the boutique and take home curated souvenirs.",
      ],
      price: "AED 75",
      duration: "6 hr.",
      cancellation: "Free cancellation",
      bookNowText: "Reserve now, pay later",
      showInfoText: "Show inclusions & important info →",
    },
    {
      id:7,
      path: "dubai-aquarium",
      image: "https://images.unsplash.com/photo-1635756962089-ee9e9cfd284c?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=687",
      category: "Adventure Tours",
      rating: "4.7",
      reviews: "210",
      title: "Dive Into Wonder: Dubai Aquarium & Underwater Adventure",
      details: [
        "Explore the ‘home of luxury’, Inside Burj Al Arab, on this 90-minute tour.",
        "Accompanied by a butler, enter the Royal Suite of this 7-star hotel.",
        "Learn about its iconic design and history in this immersive experience.",
        "Experience Emirati hospitality and capture stunning moments.",
        "Visit the boutique and take home curated souvenirs.",
      ],
      price: "AED 199",
      duration: "6 hr.",
      cancellation: "Free cancellation",
      bookNowText: "Reserve now, pay later",
      showInfoText: "Show inclusions & important info →",
    },
    {
      id: 8,
      path: "helicopter-tour",
      image: "https://images.unsplash.com/photo-1707938594551-23a20304682f?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=735",
      category: "Adventure Tours",
      rating: "4.7",
      reviews: "210",
      title: "Sky High Dubai: Exclusive Helicopter Tour Experience",
      details: [
        "Explore the ‘home of luxury’, Inside Burj Al Arab, on this 90-minute tour.",
        "Accompanied by a butler, enter the Royal Suite of this 7-star hotel.",
        "Learn about its iconic design and history in this immersive experience.",
        "Experience Emirati hospitality and capture stunning moments.",
        "Visit the boutique and take home curated souvenirs.",
      ],
      price: "AED 199",
      duration: "6 hr.",
      cancellation: "Free cancellation",
      bookNowText: "Reserve now, pay later",
      showInfoText: "Show inclusions & important info →",
    },
    {
      id: 9,
      path: "yas-island-theme-park",
      image: "https://images.unsplash.com/photo-1606225791862-6b106554ccaa?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1074",
      category: "Adventure Tours",
      rating: "4.7",
      reviews: "210",
      title: "Ultimate Fun at Yas Island: Thrills & Entertainment",
      details: [
        "Explore the ‘home of luxury’, Inside Burj Al Arab, on this 90-minute tour.",
        "Accompanied by a butler, enter the Royal Suite of this 7-star hotel.",
        "Learn about its iconic design and history in this immersive experience.",
        "Experience Emirati hospitality and capture stunning moments.",
        "Visit the boutique and take home curated souvenirs.",
      ],
      price: "AED 345",
      duration: "6 hr.",
      cancellation: "Free cancellation",
      bookNowText: "Reserve now, pay later",
      showInfoText: "Show inclusions & important info →",
    },
    {
      id: 10,
      path: "excursion-tickets",
      image: "https://images.unsplash.com/photo-1636909802866-2926b29d2b34?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1170",
      category: "Adventure Tours",
      rating: "4.7",
      reviews: "210",
      title: "Exciting Dubai Excursions: Your Adventure, Your Way",
      details: [
        "Explore the ‘home of luxury’, Inside Burj Al Arab, on this 90-minute tour.",
        "Accompanied by a butler, enter the Royal Suite of this 7-star hotel.",
        "Learn about its iconic design and history in this immersive experience.",
        "Experience Emirati hospitality and capture stunning moments.",
        "Visit the boutique and take home curated souvenirs.",
      ],
      price: "AED 199",
      duration: "6 hr.",
      cancellation: "Free cancellation",
      bookNowText: "Reserve now, pay later",
      showInfoText: "Show inclusions & important info →",
    },
    {
      id: 11,
      path: "combo-packages",
      image: "https://plus.unsplash.com/premium_photo-1694475218266-b93569487419?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1170",
      category: "Adventure Tours",
      rating: "4.7",
      reviews: "210",
      title: "All-in-One Combo Packages: Explore More, Save More",
      details: [
        "Explore the ‘home of luxury’, Inside Burj Al Arab, on this 90-minute tour.",
        "Accompanied by a butler, enter the Royal Suite of this 7-star hotel.",
        "Learn about its iconic design and history in this immersive experience.",
        "Experience Emirati hospitality and capture stunning moments.",
        "Visit the boutique and take home curated souvenirs.",
      ],
      price: "AED 360",
      duration: "6 hr.",
      cancellation: "Free cancellation",
      bookNowText: "Reserve now, pay later",
      showInfoText: "Show inclusions & important info →",
    },
  ];

  return (
    <section className="space-y-8 py-10 max-w-[1200px] mx-auto">
      {tours.map((tour, index) => (
        <TourCard key={index} {...tour} />
      ))}
    </section>
  );
}
